include:
  - board: nice_nano_v2
    shield: kyria_left
  - board: nice_nano_v2
    shield: kyria_right
  - board: nice_nano_v2
    shield: cradio_left
  - board: nice_nano_v2
    shield: cradio_right
  - board: nice_nano
    shield: cradio_left
  - board: nice_nano
    shield: cradio_right
  - board: nice_nano_v2
    shield: osprette
