include:
  - board: nice_nano_v2
    shield: kyria_left
  - board: nice_nano_v2
    shield: kyria_right
  - board: nice_nano_v2
    shield: sweep_left
  - board: nice_nano_v2
    shield: sweep_right
  - board: nice_nano
    shield: sweep_left
  - board: nice_nano
    shield: sweep_right
  - board: nice_nano_v2
    shield: osprette
